# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DFPmcmc <- function(iterations, thin, Y, T, Z, X, Beta, Lambda2, Nulam, Gamma, C, Tau2, Nutau, Eta, Theta, IDstart, IDend, SigEta, SigTheta, MuEta, a) {
    .Call(`_DFPmcmc_DFPmcmc`, iterations, thin, Y, T, Z, X, Beta, Lambda2, Nulam, Gamma, C, Tau2, Nutau, Eta, Theta, IDstart, IDend, SigEta, SigTheta, MuEta, a)
}

DPmcmc <- function(iterations, thin, Y, T, Z, Beta, Lambda2, Nulam, C, Tau2, Nutau, Theta, IDstart, IDend, SigTheta, a) {
    .Call(`_DFPmcmc_DPmcmc`, iterations, thin, Y, T, Z, Beta, Lambda2, Nulam, C, Tau2, Nutau, Theta, IDstart, IDend, SigTheta, a)
}

