# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hDFPmcmc <- function(iterations, thin, Y, T, Z, X, Beta, Lambda2, Nulam, Gamma, C, Tau2, Nutau, Eta, Theta, IDstart, IDend, SigEta, SigTheta, D, MuEta, a_glo, a_loc) {
    .Call(`_hDFPmcmc_hDFPmcmc`, iterations, thin, Y, T, Z, X, Beta, Lambda2, Nulam, Gamma, C, Tau2, Nutau, Eta, Theta, IDstart, IDend, SigEta, SigTheta, D, MuEta, a_glo, a_loc)
}

hDPmcmc <- function(iterations, thin, Y, T, Z, Beta, Lambda2, Nulam, C, Tau2, Nutau, Theta, IDstart, IDend, SigTheta, D, a_glo, a_loc) {
    .Call(`_hDFPmcmc_hDPmcmc`, iterations, thin, Y, T, Z, Beta, Lambda2, Nulam, C, Tau2, Nutau, Theta, IDstart, IDend, SigTheta, D, a_glo, a_loc)
}

